apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vault-static-secret
  namespace: my-ns

spec:
  refreshInterval: 10s

  secretStoreRef:
    name: vault-backend
    kind: SecretStore

  target:
    name: my-secret-eso
    creationPolicy: Owner

  data:
    - secretKey: username
      remoteRef:
        key: my-app/config
        property: username

    - secretKey: password
      remoteRef:
        key: my-app/config
        property: password
