---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: alpine
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret-vso
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret-vso
              key: password
        command: ["/bin/sleep"]
        args: ["infinity"]
