---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret
  namespace: my-ns
spec:
  vaultAuthRef: my-vault-auth # Nom de la VaultAuth utilisé
  mount: kvv2 # Mount path
  type: kv-v2
  path:  my-app/config # Path to synchronize
  refreshAfter: 10s # Delai before refresh
  destination: 
    create: true
    name: my-secret-vso # secret name
