services:
  apps:
    image: fallewi/vaultapps:v1
    container_name: vaultapps
    environment:
      VAULT_ADDR: http://vault:8200
      ROLE_ID: d01cd0bc-4e6e-3e26-4fdf-a67f19cd674b
      SECRET_ID: cabe8ca0-7e04-8199-aac7-92a610e53197
    ports:
      - "9000:8000"

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - vault-data:/vault/file/
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: vaultdb
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "8080:80"

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: vaultdb
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "10002:8080"
volumes:
  vault-data:
